# Generated by Django 5.1.6 on 2025-03-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название розыгрыша')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='Изображение')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала розыгрыша')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания розыгрыша')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость билета')),
                ('ticket_count', models.PositiveIntegerField(default=0, verbose_name='Количество билетов')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('winning_ticket', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выигрышный билет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('winner_determined', models.BooleanField(default=False, verbose_name='Победитель определен')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_prizes', to='prizes.telegramuser', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыши',
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField(verbose_name='Номер билета')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Зарезервирован')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('reserved_until', models.DateTimeField(blank=True, null=True, verbose_name='Зарезервирован до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='prizes.prize', verbose_name='Розыгрыш')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='prizes.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-prize__is_active', '-prize__start_date', 'ticket_number'],
                'unique_together': {('prize', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='ID платежа')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Успешная оплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='prizes.prize', verbose_name='Розыгрыш')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='prizes.telegramuser', verbose_name='Пользователь')),
                ('tickets', models.ManyToManyField(related_name='payment', to='prizes.ticket', verbose_name='Билеты')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
