# Generated by Django 5.1.6 on 2025-03-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название приза'),
        ),
    ]
