# Generated by Django 5.1.6 on 2025-03-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_alter_prize_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа'),
        ),
    ]
