# Generated by Django 5.1.6 on 2025-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
