# Generated by Django 5.1.6 on 2025-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0005_telegramuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='chat_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в чате'),
        ),
    ]
