# Generated by Django 5.1.6 on 2025-03-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0006_prize_chat_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='winner_determined',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='winning_ticket',
        ),
    ]
