# Generated by Django 5.1.6 on 2025-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0007_remove_prize_winner_remove_prize_winner_determined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='text',
            field=models.TextField(default=' ', verbose_name='Текст FAQ'),
            preserve_default=False,
        ),
    ]
